kind: Deployment
apiVersion: apps/v1
metadata:
  name: hellokube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
        - name: hellokube
          image: anu26092002/hellokube
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always