apiVersion: v1
kind: Service
metadata:
  name: hellokube
spec:
  selector:
    app: hellokube
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30096
  type: NodePort    
  